"""next_crm URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function viewsopportunity/updateopportunitystate
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from next_crm.views import Google, Auth, Dashboard, Settings, Contacts,  Calender, Users, Account, General, \
    Opportunities, Cron, Payment, EmailTemplate, SalersOrder, Products, Quotations, Invoice, \
    Sales, Pricelist, QuotTemplate, Salesteams, DeliveryMethod, PaymentTerm, UnitofMeasure, CustomerInvoice, Tags,Stripe

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', Auth.login_view),
    url(r'^admin/', admin.site.urls),
    url(r'^register/', Auth.register),
    url(r'^company-wizard/', Auth.company_wizard_step_one),
    url(r'^user-invite/', Auth.company_wizard_step_two),
    url(r'^welcome', Auth.company_wizard_welcome),
    url(r'^login/', Auth.login_view),
    url(r'^logout/', Auth.logout_view),
    url(r'^forgot-password/', Auth.forgot_password),
    url(r'^reset-password/(\w+)/$', Auth.reset_password),
    url(r'^dashboard/', Dashboard.index),
    url(r'^sales/', Sales.sales),
    url(r'^line-chart/', Sales.getChartsData),
    url(r'^user-modules/', Dashboard.modules),
    url(r'^apps/', Dashboard.apps),
    url(r'^layoutsetting/', Settings.setting),
    url(r'^contact/list/', Contacts.list),
    url(r'^customer/list/', Contacts.list),
    url(r'^contact/list_ajax/', Contacts.list_ajax),
    url(r'^contact/index/', Contacts.index),

    url(r'^contact/add/', Contacts.add),
    url(r'^contact/tags/', Tags.get_tags),
    url(r'^update/tag/', Tags.update_tag),
    url(r'^contact/tag_create/', Tags.create_tag),
    url(r'^contact/company/', Contacts.company),
    url(r'^contact/save/', Contacts.save),
    url(r'^contact/company_create_edit/', Contacts.company_create_edit),
    url(r'^contact/company_create/', Contacts.company_create),
    url(r'^contact/view/([\w-]+)/$', Contacts.view),
    url(r'^contact/edit/([\w-]+)/$', Contacts.edit),
    url(r'^contact/view_ajax/([\w-]+)/$', Contacts.view_ajax),
    url(r'^contact/update_ajax/([\w-]+)/$', Contacts.update_ajax),
    url(r'^contact/update/', Contacts.update),
    url(r'^contact/upload/', Contacts.simple_upload),
    url(r'^contact/import/', Contacts.contact_import),
    url(r'^contact/mapping/', Contacts.contact_import_mapping),

    url(r'^contact/msg_attatch/', Contacts.message_attatchments),
    url(r'^contact/export/', Contacts.contact_export),
    url(r'^contact/customer/', Contacts.customer_list),
    url(r'^contact/customeremail/', Contacts.contact_listemail),
    url(r'^message/search_contact/', General.get_contacts_by_keyword),
    url(r'^message/send_msg/', General.send_message),
    url(r'^contact/delete/', Contacts.delete_contacts),
    url(r'^calendar/list/', Calender.list),
    url(r'^calendar/list/(\w+)/$', Calender.list),
    url(r'^calender/event_save/', Calender.event_save),
    url(r'^calender/delete_event/', Calender.delete_event),
    url(r'^calender/meetings/', Calender.get_all_meetings),
    url(r'^calender/get_attendies/', Calender.get_attendies),
    url(r'^calender/search_attendies/', Calender.search_attendies),
    url(r'^calender/favorite/', Calender.get_favorite),
    url(r'^google/connect/', Google.google_connect),
    url(r'^google/auth/', Google.oauth2callback),
    url(r'^google/google_sync/', Google.google_sync),

    url(r'^user/list/', Users.user_list),
    url(r'^user/create/', Users.user_create),
    url(r'^user/save/', Users.user_save),
    url(r'^user/all_users/', Users.get_all_user),
    url(r'^user/user_detail/', Auth.user_detail),
    url(r'^user/view/(\d+)/$', Users.user_view),
    url(r'^user/get-user/(\d+)/$', Users.get_user),
    url(r'^user/profile/', Users.profile),
    url(r'^user/image-upload/', Users.profile_image_upload),
    url(r'^user/get-profile/', Users.get_profile),

    url(r'^user/activate/(\w+)/$', Users.user_activate),
    url(r'^user/invite/activate/(\w+)/$', Auth.invite_user_activate),
    url(r'^user/delete/', Users.user_delete),
    url(r'^user/change-status/', Users.user_change_status),
    url(r'^price-online/', Account.payment),

    url(r'^payment_step_1/', Account.payment_step_1),
    url(r'^payment_step_2/', Account.payment_step_2),
    #url(r'^pp/', Account.payment_step_3),
    url(r'^payment_step_3/', Account.payment_step_3),
    url(r'^my-price/', Stripe.price_list_ajax),

    url(r'^paymentProcess/', Account.paymentProcess),
    url(r'^thank-you/', Account.thank_you),
    url(r'^installed-application/', Dashboard.installed_applications),
    url(r'^install-application/', Dashboard.install_applications),
    url(r'^uninstall-application/', Dashboard.uninstall_applications),
    url(r'^next-activity/', General.next_activity),
    url(r'^fetch_activity/', General.fetch_activity),
    url(r'^notification/', General.notification_activity),
    url(r'^mark_read/', General.mark_read),
    url(r'^delete-activity/', General.delete_activity),
    url(r'^company/setting/', Users.company_settings),
    url(r'^company/get_company_info/', Users.get_company_info),
    url(r'^company/save/', Users.company_save),

    url(r'^general/getMessageData/(?P<m_id>[\w-]+)$', General.getMessageData),
    url(r'^general/MessageDelete/(?P<m_id>[\w-]+)$', General.MessageDelete),
    url(r'^general/message_create/', General.message_create),
    url(r'^general/get_message/', General.get_message),
    url(r'^general/logactivity/', General.logactivity),
    url(r'^general/activity_change/', General.activity_change),
    url(r'^general/fetch_country/', General.fetch_country),
    url(r'^general/rm_file/', General.remove_file_from_path),


    url(r'^pricelist/list/', Pricelist.list),
    url(r'^pricelist/listdata/', Pricelist.listdata),
    url(r'^pricelist/add/', Pricelist.add),
    url(r'^pricelist/adddata/', Pricelist.adddata),

    url(r'^users/user_list/', Users.user_list),
    url(r'^users/user_create/', Users.user_create),
    url(r'^users/save/', Users.user_save),
    url(r'^users/all_users/', Users.get_all_user),
    url(r'^users/user_detail/', Auth.user_detail),
    url(r'^users/view/(\d+)/$', Users.user_view),
    url(r'^users/get_user/(\d+)/$', Users.get_user),
    url(r'^users/activate/(\w+)/$', Users.user_activate),
    url(r'^users/delete/', Users.user_delete),

    url(r'^sales/', Sales.sales),
    url(r'^cron/automatedinvoiceemail/', Cron.automatedinvoiceemail),
    url(r'^cron/reminder_email/', Cron.reminder_email),
    url(r'^opportunity/list/', Opportunities.list),
    url(r'^opportunity/list/(?P<viewtype>[\w-]+)', Opportunities.list),
    url(r'^opportunity/list/(?P<viewtype>[\w-]+)/next_activity', Opportunities.list),
    url(r'^opportunity/listdata/', Opportunities.listdata),

    #url(r'^opportunity/updateopportunitystate/', Opportunities.updateopportunitystate),
    url(r'^opportunity/updateopertunityorder/', Opportunities.updateopertunityorder),
    url(r'^opportunity/updatecolumnorder/', Opportunities.updatecolumnorder),
    url(r'^opportunity/savecolumn/', Opportunities.savecolumn),
    url(r'^opportunity/save/', Opportunities.saveOpportunty),
    url(r'^opportunity/updateopportunitycolor/', Opportunities.updateopportunitycolor),
    url(r'^opportunity/updateopportunityrating/', Opportunities.updateopportunityrating),
    url(r'^opportunity/updateopportunitystatus/', Opportunities.updateopportunitystatus),
    url(r'^opportunity/delete/$', Opportunities.delete_opportunity),
    url(r'^opportunity/updatecolumnfold/', Opportunities.updatecolumnfold),
    url(r'^opportunity/updatecolumnstatus/', Opportunities.updatecolumnstatus),
    url(r'^opportunity/updatecolumnarchive/',Opportunities.updatecolumnarchive),
    url(r'^opportunity/add/', Opportunities.add),
    url(r'^opportunity/adddata/', Opportunities.adddata),
    url(r'^opportunity/edit/(\d+)/$', Opportunities.edit),
    url(r'^opportunity/editdata/(?P<edit_id>[\w-]+)/$', Opportunities.editdata),
    url(r'^opportunity/editSave/', Opportunities.editsave),
    #url(r'^opportunity/updateopportunitystate/', Opportunities.updateopportunitystate),
    url(r'^opportunity/updateopportunitylostreason/', Opportunities.updateopportunitylostreason),
    url(r'^opportunity/view/(\d+)/$', Opportunities.view),
    url(r'^opportunity/viewdata/(?P<view_id>[\w-]+)/$', Opportunities.viewdata),
    url(r'^opportunity/getLostreasonByid/(?P<lr_id>[\w-]+)/$', Opportunities.getLostreasonByid),
    url(r'^opportunity/get-lost-reason/', Opportunities.get_lost_reason),
    url(r'^opportunity/addlostreason/', Opportunities.addlostreason),
    url(r'^opportunity/addTags', Opportunities.addTags),
    url(r'^opportunity/editcolumn/(?P<col_id>[\w-]+)/$', Opportunities.editcolumn),
    url(r'^opportunity/updatecolumn/', Opportunities.updatecolumn),
    url(r'^opportunity/addteam/', Opportunities.addteam),
    url(r'^opportunity/getTeamData/(?P<team_id>[\w-]+)$', Opportunities.getTeamData),
    url(r'^opportunity/attachment/', Opportunities.attachment),
    url(r'^opportunity/attachedfiledelete/', Opportunities.attachedfiledelete),
    url(r'^opportunity/getUserData/(?P<user_id>[\w-]+)$', Opportunities.getUserData),
    url(r'^opportunity/get_lead_source/', Opportunities.get_lead_source),
    url(r'^opportunity/saveUser', Opportunities.saveUser),
    url(r'^opportunity/opportunityAction', Opportunities.opportunityAction),
    url(r'^opportunity/addLeadsource/', Opportunities.addLeadsource),
    url(r'^opportunity/getLeadsourceData/(?P<id>[\w-]+)$', Opportunities.getLeadsourceData),
    url(r'^opportunity/addteamuser', Opportunities.addteamuser),
    url(r'^opportunity/opportunityexport', Opportunities.opportunityexport),

    url(r'^opportunity/get_sales_team/', Opportunities.get_sales_team),
    url(r'^opportunity/get_sales_persion/', Opportunities.get_sales_person),

    url(r'^salesteams/list/', Salesteams.list),
    url(r'^salesteams/add/', Salesteams.add),
    url(r'^salesteams/listdata/', Salesteams.listdata),
    url(r'^salesteams/adddata/', Salesteams.adddata),

    url(r'^salesteams/edit/(?P<edit_id>[\w-]+)/$', Salesteams.edit),
    url(r'^salesteams/editdata/(?P<edit_id>[\w-]+)/$', Salesteams.editdata),
    url(r'^salesteams/saveteam/', Salesteams.saveteam),
    url(r'^salesteams/deletesales/', Salesteams.deletesales),

    url(r'^quotation/list/', Quotations.list),
    url(r'^quotation/listdata/', Quotations.listdata),
    url(r'^quotation/add/', Quotations.add),
    url(r'^quotation/preview/(?P<preview_id>[\w-]+)/(?P<previewtype>[\w-]+)$', Quotations.preview),

    url(r'^quotation/adddata/', Quotations.adddata),
    url(r'^quotation/saveQuatation/', Quotations.saveQuatation),
    url(r'^quotation/getUomListdata/', Quotations.getUomListdata),
    url(r'^quotation/getTaxesListdata/', Quotations.getTaxesListdata),
    url(r'^quotation/view/([\w-]+)/$', Quotations.view),
    url(r'^quotation/viewdata/([\w-]+)/$', Quotations.viewdata),
    url(r'^quotation/edit/([\w-]+)/$', Quotations.edit),
    url(r'^quotation/edit/(?P<edit_id>[\w-]+)/(?P<status>[a-zA-Z]+)$', Quotations.edit),
    url(r'^quotation/editdata/([\w-]+)/$', Quotations.editdata),
    url(r'^quotation/updateQuatation/', Quotations.updateQuatation),
    #url(r'^quotation/getTemplateDataByID/', Quotations.getTemplateDataByID),
    url(r'^quotation/sendQuoteEmail/', Quotations.sendQuoteEmail),
    #url(r'^quotation/sendEmailDate/', Quotations.sendEmailDate),
    url(r'^quotation/deleteQoutation/', Quotations.deleteQoutation),
    url(r'^quotation/saveEmailtemplate/', Quotations.saveEmailtemplate),
    url(r'^quotation/getEmailTemplate/([\w-]+)/$', Quotations.getEmailTemplate),
    #url(r'^quotation/getEmailData/', Quotations.getEmailData),
    url(r'^quotation/upload_file/', Quotations.email_upload_file),
    url(r'^quotation/remove-email-file/', Quotations.remove_email_file),
    #url(r'^quotation/upload_file1/', Quotations.upload_file1),
    url(r'^quotation/quotationexport', Quotations.quotationexport),
    url(r'^quotation/getEmailTemplateData/(?P<email_template_id>[\w-]+)$', Quotations.getEmailTemplateData),
    url(r'^payment/list/', Payment.list),
    url(r'^payment/listdata/', Payment.listdata),
    url(r'^payment/add/', Payment.add),
    url(r'^payment/adddata/', Payment.adddata),
    url(r'^payment/view/(?P<view_id>[\w-]+)/$', Payment.view),
    url(r'^payment/viewdata/(?P<view_id>[\w-]+)/$', Payment.viewdata),
    url(r'^payment/edit/(?P<edit_id>[\w-]+)/$', Payment.edit),
    url(r'^payment/editdata/(?P<edit_id>[\w-]+)/$', Payment.editdata),
    url(r'^payment/deletePayment/', Payment.deletePayment),
    url(r'^payment/paymentexport/', Payment.paymentexport),


    url(r'^sales/order/list/', SalersOrder.list),
    url(r'^salers/order/listdata/', SalersOrder.listdata),
    url(r'^sales/order/test/', SalersOrder.listdata),
    url(r'^sales/order/add/', SalersOrder.add),
    url(r'^sales/order/preview/(?P<preview_id>[\w-]+)/$', SalersOrder.preview),
    url(r'^sales/order/adddata/', SalersOrder.adddata),


    url(r'^sales/order/getUomListdata/', SalersOrder.getUomListdata),
    url(r'^sales/order/getTaxesListdata/', SalersOrder.getTaxesListdata),
    url(r'^sales/order/view/([\w-]+)/$', SalersOrder.view),
    url(r'^sales/order/viewdata/(?P<view_id>[\w-]+)/$', SalersOrder.viewdata),
    url(r'^sales/order/edit/(?P<edit_id>[\w-]+)/$', SalersOrder.edit),
    url(r'^sales/order/edit/(?P<edit_id>[\w-]+)/(?P<status>[a-zA-Z]+)$', SalersOrder.edit),
    url(r'^sales/order/editdata/(?P<edit_id>[\w-]+)/$', SalersOrder.editdata),

    url(r'^sales/order/getTemplateDataByID/', SalersOrder.getTemplateDataByID),
    url(r'^sales-order/updateQuotStatus/', SalersOrder.updateQuotStatus),
    url(r'^sales/order/sendQuoteEmail/', SalersOrder.sendQuoteEmail),
    url(r'^sales/order/deleteQoutation/', SalersOrder.deleteQoutation),
    url(r'^sales/order/salersexport/', SalersOrder.salersexport),
    url(r'^quotation/default-template/([\w-]+)/$', Quotations.get_default_template),

    url(r'^product/list/', Products.list),
    url(r'^product/get-product/', Products.get_product),
    url(r'^product/get-product-unit/', Products.get_product_unit),
    url(r'^product/get-taxes/', Products.get_tax),
    url(r'^product/get-uom-category/', Products.get_unit_category),
    url(r'^product/get-product-category/', Products.get_product_category),
    url(r'^product/get-sales-person/', Products.get_sales_person),
    url(r'^product/listdata/', Products.listdata),
    url(r'^product/getlistdata/', Products.getlistdata),
    url(r'^product/add/', Products.add),
    url(r'^product/adddata/', Products.adddata),
    url(r'^product/save/', Products.save),
    url(r'^product/categorysave/', Products.categorysave),
    url(r'^product/categorydataByid/(?P<cate_id>[\w-]+)$', Products.categorydataByid),
    url(r'^product/getCategory/', Products.getCategory),
    url(r'^product/getUomCategory/', Products.getUomCategory),
    url(r'^product/uomsave/', Products.saveUOM),
    url(r'^product/getUomCById/(?P<uom_id>[\w-]+)$', Products.getUomCById),
    url(r'^product/uomCateByid/(?P<uom_cate_id>[\w-]+)$', Products.uomCateByid),
    url(r'^product/save-uom-cat/', Products.saveUOMCate),
    url(r'^product/view/([\w-]+)/$', Products.view),
    url(r'^product/viewdata/([\w-]+)/$', Products.viewdata),
    url(r'^product/edit/(?P<edit_id>[\w-]+)/$', Products.editProduct),
    url(r'^product/editdata/([\w-]+)/$', Products.editdata),
    url(r'^product/update/', Products.update),
    url(r'^product/upload_img/', Products.upload_img),
    url(r'^product/saveTaxes/', Products.saveTaxes),
    url(r'^product/getTaxesById/(?P<tax_id>[\w-]+)$', Products.getTaxesById),
    url(r'^product/deleteproducts/', Products.deleteProducts),
    url(r'^product/Paginglimit/', Products.Paginglimit),
    url(r'^product/productexport/', Products.productexport),

    url(r'^quot/template/add/', QuotTemplate.add),
    url(r'^quot/template/adddata/', QuotTemplate.adddata),
    url(r'^quot/template/saveTemplate/', QuotTemplate.saveTemplate),
    url(r'^quot/template/list/', QuotTemplate.list),
    url(r'^quot/template/listdata/', QuotTemplate.listdata),
    url(r'^quot/template/view/([\w-]+)/$', QuotTemplate.view),
    url(r'^quot/template/viewdata/([\w-]+)/$', QuotTemplate.viewdata),
    url(r'^quot/template/edit/([\w-]+)/$', QuotTemplate.edit),
    url(r'^quot/template/editdata/([\w-]+)/$', QuotTemplate.editdata),
    url(r'^quot/template/updateTemplate/', QuotTemplate.updateTemplate),
    url(r'^quot/template/deletetemplate/', QuotTemplate.deletetemplate),
    url(r'^quot/get-quot-template/', QuotTemplate.get_quot_template_term),
    url(r'^email/template/add/', EmailTemplate.add),
    url(r'^email/template/adddata/', EmailTemplate.adddata),
    url(r'^email/template/list/', EmailTemplate.list),
    url(r'^email/template/listdata/', EmailTemplate.listdata),
    url(r'^email/template/view/(?P<view_id>[\w-]+)$', EmailTemplate.view),
    url(r'^email/template/viewdata/(?P<view_id>[\w-]+)$', EmailTemplate.viewdata),
    url(r'^email/template/edit/([\w-]+)/$', EmailTemplate.edit),
    url(r'^email/template/editdata/([\w-]+)/$', EmailTemplate.editdata),
    url(r'^email/template/updateTemplate/', EmailTemplate.updateTemplate),
    url(r'^email/template/deleteemailtemplate/', EmailTemplate.deleteemailtemplate),
    url(r'^delivery/method/add/', DeliveryMethod.add),
    url(r'^delivery/method/save/', DeliveryMethod.save),
    url(r'^delivery/method/list/', DeliveryMethod.list),
    url(r'^delivery/method/listdata/', DeliveryMethod.listdata),
    url(r'^delivery/method/view/(?P<view_id>[\w-]+)$', DeliveryMethod.view),
    url(r'^delivery/method/viewdata/(?P<view_id>[\w-]+)$', DeliveryMethod.viewdata),
    url(r'^delivery/method/edit/(?P<edit_id>[\w-]+)$', DeliveryMethod.edit),
    url(r'^delivery/method/editdata/(?P<edit_id>[\w-]+)$', DeliveryMethod.editdata),
    url(r'^delivery/method/update', DeliveryMethod.update),
    url(r'^delivery/method/deletedelivery/', DeliveryMethod.deletedelivery),
    url(r'^delivery/method/savepricingrules/', DeliveryMethod.savepricingrules),
    url(r'^delivery/method/deletepricingrules/', DeliveryMethod.deletepricingrules),
    url(r'^delivery/method/getCountry/', DeliveryMethod.getCountry),
    url(r'^delivery/method/addCountry', DeliveryMethod.addCountry),
    url(r'^delivery/method/getpricingData/(?P<price_id>[\w-]+)/$', DeliveryMethod.getpricingData),
    url(r'^delivery/method/adddata/', DeliveryMethod.adddata),

    url(r'^payment/term/add/', PaymentTerm.add),
    url(r'^payment/term/save/', PaymentTerm.save_payment_term),
    url(r'^payment/term/saveTerm/', PaymentTerm.saveTerm),
    url(r'^payment/term/list/', PaymentTerm.list),
    url(r'^payment/term/listdata/', PaymentTerm.listdata),
    url(r'^payment/term/view/([\w-]+)/$', PaymentTerm.view),
    url(r'^payment/term/viewdata/([\w-]+)/$', PaymentTerm.viewdata),
    url(r'^payment/term/edit/([\w-]+)/$', PaymentTerm.edit),
    url(r'^payment/term/editdata/([\w-]+)/$', PaymentTerm.editdata),
    url(r'^payment/term/update', PaymentTerm.update),
    url(r'^payment/term/OrderUpdate', PaymentTerm.OrderUpdate),
    url(r'^payment/term/deletepayment/', PaymentTerm.deletepayment),
    url(r'^payment/term/deleteterm/', PaymentTerm.deleteterm),
    url(r'^payment/term/getTermData/([\w-]+)/$', PaymentTerm.getTermData),
    url(r'^payment/term/getPaymentTermById/(?P<payment_term_id>[\w-]+)$', PaymentTerm.getPaymentTermById),
    url(r'^payment/get-payment-term/', PaymentTerm.get_payment_term),

    url(r'^unit/of/measure/add/', UnitofMeasure.add),
    url(r'^unit/of/measure/list/', UnitofMeasure.list),
    url(r'^unit/of/measure/listdata/', UnitofMeasure.listdata),
    url(r'^unit/of/measure/view/(?P<view_id>[\w-]+)$', UnitofMeasure.view),
    url(r'^unit/of/measure/viewdata/(?P<view_id>[\w-]+)$', UnitofMeasure.viewdata),
    url(r'^unit/of/measure/edit/(?P<edit_id>[\w-]+)$', UnitofMeasure.edit),
    url(r'^unit/of/measure/editdata/(?P<edit_id>[\w-]+)$', UnitofMeasure.editdata),
    url(r'^unit/of/measure/update', UnitofMeasure.update),
    url(r'^unit/of/measure/deleteunit/', UnitofMeasure.deleteunit),

    url(r'^customer/invoice/add/', CustomerInvoice.add),
    url(r'^customer/invoice/list/', CustomerInvoice.list),
    url(r'^customer/invoice/customerlist/([\w-]+)/$', CustomerInvoice.customerlist),
    url(r'^customer/invoice/listdata/', CustomerInvoice.listdata),
    url(r'^customer/invoice/view/([\w-]+)/$', CustomerInvoice.view),
    url(r'^customer/invoice/viewdata/([\w-]+)/$', CustomerInvoice.viewdata),
    url(r'^customer/invoice/customerinvoicelistdata/([\w-]+)/$', CustomerInvoice.customerinvoicelistdata),
    url(r'^customer/invoice/edit/([\w-]+)/$', CustomerInvoice.edit),
    url(r'^customer/invoice/editdata/([\w-]+)/$', CustomerInvoice.editdata),
    url(r'^customer/invoice/updateInvoice', CustomerInvoice.updateInvoice),
    url(r'^customer/invoice/saveCustomerInvoice', CustomerInvoice.saveCustomerInvoice),
    url(r'^customer/invoice/RegistrationPayment', CustomerInvoice.RegistrationPayment),
    url(r'^customer/invoice/getPaymentRegisterData', CustomerInvoice.getPaymentRegisterData),
    url(r'^customer/invoice/deletecustomer', CustomerInvoice.deletecustomer),
    url(r'^customer/invoice/Checksendmail', CustomerInvoice.Checksendmail),
    url(r'^customer/invoice/CancelChecksendmail', CustomerInvoice.CancelChecksendmail),
    url(r'^customer/invoice/customerinvoicetotal/([\w-]+)/$', CustomerInvoice.customerinvoicetotal),
    url(r'^customer/invoice/CreateInvoice/', CustomerInvoice.CreateInvoice),
    url(r'^customer/invoice/AutoCreateInvoice/', CustomerInvoice.AutoCreateInvoice),
    url(r'^customer/invoice/get_invoice_data/', CustomerInvoice.get_invoice_data),

    url(r'^customer/invoice/UpdateInvoiceStatus/$', CustomerInvoice.UpdateInvoiceStatus),
    url(r'^customer/invoice/invoiceexport', CustomerInvoice.invoiceexport),
    url(r'^customer/invoice/Unreconcile/(?P<invoice_id>[\w-]+)$', CustomerInvoice.Unreconcile),
    url(r'^product/getTaxesById/(?P<tax_id>[\w-]+)$', Products.getTaxesById),

    url(r'^sales-order/document/([\w\:-]+)/$', SalersOrder.sales_pdf),
    url(r'^quotation/document/([\w\:-]+)/$', Quotations.pdf_download),
    url(r'^quotation/document_header/([\w\:-]+)/([\w-]+)/$', Quotations.document_header),
    url(r'^quotation/document_footer/([\w\:-]+)/$', Quotations.document_footer),
    url(r'^htm/([\w\:-]+)/([\w-]+)/$', Quotations.pdf_html),

    url(r'^invoice/document/([\w\:-]+)/$', CustomerInvoice.pdf_download),
    url(r'^invoice/invoice_header/([\w\:-]+)/([\w-]+)/$', CustomerInvoice.invoice_header),
    url(r'^invoice/invoice_footer/([\w\:-]+)/$', CustomerInvoice.invoice_footer),
    url(r'^htmin/([\w\:-]+)/$', CustomerInvoice.pdf_html),

    url(r'^sales-order/get-product-data/$', SalersOrder.get_product_data),
    url(r'^general/fetch_all_users/', General.fetch_all_user),
	url(r'^general/get_customer_details/', General.get_customer_detail),
    url(r'^general/fetch_all_admin_users/', General.fetch_all_admin),
    url(r'^general/fetch_company_user/', General.fetch_company_user),
    url(r'^general/stripe_payments/', General.fetch_stripe_payments),
    url(r'^generate_pdf/([\w\:-]+)/([\w-]+)/$', General.generate_pdf),
    url(r'^get_recipient/$', General.get_recipient),
    url(r'^stripe/get_invoices/', Stripe.stripe_invoices),
    url(r'^price-list/', Stripe.price_list),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)